Extract Conn interface and add CompositeConn implementation for interacting with services exposed directly rather than via MMD
peak6/go-mmd pull request #19
Opened 2021-01-05 19:38 UTC by ryant1986

2021-01-05 20:21 UTC, pkuprys requested changes
missed a few ERROR accessMethod returns

2021-01-05 20:21 UTC, pkuprys commented on mmd/compositeconn.go
> +		return -1, err
```suggestion
		return ERROR, err
```

2021-01-05 20:21 UTC, pkuprys commented on mmd/compositeconn.go
> +		return -1, err
```suggestion
		return ERROR, err
```

2021-01-05 20:21 UTC, pkuprys commented on mmd/compositeconn.go
> +		return -1, fmt.Errorf("service discovery service response was not a map: %s", reflect.TypeOf(resp))
```suggestion
		return ERROR, fmt.Errorf("service discovery service response was not a map: %s", reflect.TypeOf(resp))
```

2021-01-05 20:26 UTC, ryant1986 commented on mmd/compositeconn.go
> +		return -1, err
done

2021-01-05 20:26 UTC, ryant1986 commented on mmd/compositeconn.go
> +		return -1, err
done

2021-01-05 20:26 UTC, ryant1986 commented on mmd/compositeconn.go
> +		return -1, fmt.Errorf("service discovery service response was not a map: %s", reflect.TypeOf(resp))
done

2021-01-05 21:15 UTC, pkuprys approved these changes
looks good

2021-01-07 14:10 UTC, jlobraco approved these changes
lgtm

2021-01-14 15:18 UTC, merged