fix k8s env var check
peak6/go-mmd pull request #21
Opened 2021-01-27 15:11 UTC by ryant1986

2021-01-27 18:55 UTC, yangxizi030 approved these changes
lgtm

2021-01-27 19:04 UTC, pkuprys requested changes
just one question

2021-01-27 19:04 UTC, pkuprys commented on mmd/compositeconn.go
> +var _, isInK8s = os.LookupEnv("KUBERNETES_SERVICE_HOST")
Is it possible for "KUBERNETES_SERVICE_HOST" to be empty or non-truthy, implying that it is NOT in k8s?

2021-01-27 19:06 UTC, ryant1986 commented on mmd/compositeconn.go
> +var _, isInK8s = os.LookupEnv("KUBERNETES_SERVICE_HOST")
if that is the case, then `isInK8s` will be `false` which is what I want.  If it's set to anything, `isInK8s` will be `true`, which is what I want.  Am I missing something?

2021-01-28 15:02 UTC, ryant1986 commented on mmd/compositeconn.go
> +var _, isInK8s = os.LookupEnv("KUBERNETES_SERVICE_HOST")
I see what you're saying.  I don't think it's possible or a case we need to worry about

2021-01-29 20:49 UTC, pkuprys approved these changes
lgtm

2021-01-29 20:49 UTC, merged