Explicitly configure whether or not to use istio ingress
peak6/go-mmd pull request #24
Opened 2021-02-24 19:53 UTC by ryant1986

2021-02-25 13:43 UTC, yangxizi030 requested changes

2021-02-25 13:43 UTC, yangxizi030 commented on mmd/compositeconn.go
> +var useIstioIngress = getEnvBool("USE_ISTIO_INGRESS", !isInK8s)
Can we put these variables inside the function use them? so we don't need to evaluate them if those functions don't get called

2021-02-25 13:43 UTC, yangxizi030 commented on mmd/compositeconn.go
> +		var result, _ = strconv.ParseBool(value)
maybe check if parse success here

2021-02-25 13:47 UTC, jlobraco approved these changes
lgtm

2021-02-25 15:16 UTC, ryant1986 commented on mmd/compositeconn.go
> +var useIstioIngress = getEnvBool("USE_ISTIO_INGRESS", !isInK8s)
I think this is preferable to performing the lookups every time they're used

2021-02-25 15:23 UTC, ryant1986 commented on mmd/compositeconn.go
> +		var result, _ = strconv.ParseBool(value)
What do you think the right course of action is if it's a parse failure, panic?  I used this approach (consider the value false if it's uparseable), but failing fast for invalid config probably makes more sense..

2021-02-25 20:10 UTC, jlobraco commented on mmd/compositeconn.go
> +		var result, _ = strconv.ParseBool(value)
I think a panic is acceptable here given the environment variable has been set, but it is not parsable as a bool, we would probably want to know that right away. Nice catch Xizi.

2021-02-25 20:14 UTC, jlobraco commented on mmd/compositeconn.go
> +var useIstioIngress = getEnvBool("USE_ISTIO_INGRESS", !isInK8s)
I agree with Ryan here. We could wrap them in a function with a do once block but IMO that would be adding unnecessary indirection. I say we can leave this as it is.

2021-02-25 20:46 UTC, ryant1986 commented on mmd/compositeconn.go
> +		var result, _ = strconv.ParseBool(value)
Done, and moved these methods to mmd.go so that connconfig.go can also use them

2021-02-26 14:34 UTC, yangxizi030 approved these changes
looks good!

2021-02-26 14:40 UTC, merged