lock socket when reconnect
peak6/go-mmd pull request #34
Opened 2021-09-03 21:19 UTC by xizi-030

2021-09-07 12:53 UTC, jlobraco requested changes
I must be missing something. I fail to see what this lock is protecting against.

Also, this will hold the lock while it is trying to reconnect to the mmd, which could be forever.

2021-09-08 12:38 UTC, xizi-030 commented
> I must be missing something. I fail to see what this lock is protecting against.
> 
> Also, this will hold the lock while it is trying to reconnect to the mmd, which could be forever.

My thought on the lock was 
```
TED disconnect --> close socket --> new TCP socket -> call onConnect(subscribe SUB) error out because SUB closed the socket
SUB disconnect -------------------------------------------------> close socket ------------> new TCP socket
```
But I think it might cause bad behavior if we call OnConnect multiple times when lots of service on that composite connection disconnect, so I made some changes make it clear all in memory connection and start fresh when there is service disconnect like previous MMD does.

2021-09-09 13:27 UTC, minkeelee approved these changes
lgtm

2021-09-09 13:33 UTC, jlobraco requested changes

2021-09-09 13:33 UTC, jlobraco commented on mmd/compositeconn.go
>  	err = c.mmdConn.close()
I believe that because we are calling the `CompositeConn.onDisconnect()` that the `mmdConn`'s `cleanupReader`/`cleanupSocket` will never be called.

2021-09-09 13:33 UTC, jlobraco commented on mmd/compositeconn.go
> +	"go.uber.org/atomic"
What version of atomic are you using? I can't get goland to recognize this type.

2021-09-09 13:45 UTC, xizi-030 commented on mmd/compositeconn.go
>  	err = c.mmdConn.close()
not sure if i get it right. `CompositeConn.onDisconnect()` calls `c.close()` -> 
```
for service, conn := range c.conns {
		conn.cleanupReader()
		conn.cleanupSocket()
```

2021-09-09 14:43 UTC, jlobraco commented on mmd/compositeconn.go
>  	err = c.mmdConn.close()
Right, this calls the cleanup functions on all of the direct connections in the `conns` slice of the composite connection. However, the composite connection _also_ has a separate `mmdConn` that in this `close` function _only_ calls `mmdConn.close()` but never calls the cleanup function on it.

2021-09-09 14:46 UTC, xizi-030 commented on mmd/compositeconn.go
>  	err = c.mmdConn.close()
ah get it! fixed

2021-09-09 14:47 UTC, jlobraco approved these changes

2021-09-13 12:59 UTC, jlobraco approved these changes

2021-09-15 21:43 UTC, pkuprys requested changes
added a few questions and comments.

I am still trying to wrap my head around the counter piece, wondering if a whiteboarding session might be in order for that

2021-09-15 21:43 UTC, pkuprys commented on mmd/conn.go
> +	c.socket = nil
Should we be doing this in the block above?

2021-09-15 21:51 UTC, xizi-030 commented on mmd/conn.go
> +				connectionFailed = true
hmm i think I pushed some changes while the comment was pending. changed the logic to log by timing now because this will still spam some logs

2021-09-15 21:55 UTC, xizi-030 commented on mmd/conn.go
> +	c.socket = nil
done

2021-09-15 21:55 UTC, xizi-030 commented on mmd/compositeconn.go
> +				log.Println("Closing and reconnect composite connection")
done

2021-09-15 22:03 UTC, xizi-030 commented on mmd/compositeconn.go
> +		conn.close() // error expected here since it could be a disconnected service
i don't think so because in composite connection it exits from the reader loop is mostly from the connection get closed. Also `cleanupReader` and `cleanupSocket` is already closed the read and write part of the socket.

2021-09-16 14:52 UTC, pkuprys commented on mmd/compositeconn.go
> +	stopCounter      *atomic.Int32
per offline conversation, can we rename this to exclude `stop`? Some ideas , but open to anything:
```
connAttempts
connCounter
connVersionTracker
```

2021-09-16 14:53 UTC, pkuprys commented on mmd/compositeconn.go
> +func (c *CompositeConn) onDisconnect(connCounter int32) {
per offline, remove `er` from here, and maybe rename
```suggestion
func (c *CompositeConn) onDisconnect(connCount int32) {
```

2021-09-16 14:55 UTC, pkuprys commented on mmd/connconfig.go
> +	Counter           int32
per offline, remove `er`, and maybe rename (this name is Y.A.S. (yet another suggestion, open to other ideas too))
```suggestion
	LastConnVersion           int32
```

2021-09-16 18:48 UTC, merged