Core 1036 panic if no env set
peak6/go-mmd pull request #36
Opened 2021-10-04 21:44 UTC by op863118

2021-10-04 21:50 UTC, ryant1986 approved these changes

2021-10-04 21:52 UTC, xizi-030 approved these changes
lgtm

2021-10-05 12:47 UTC, jlobraco requested changes

2021-10-05 12:47 UTC, jlobraco commented on mmd/conn.go
> +		fmt.Printf("Unknown channel: %v discarding message", cid)
This will no longer print a newline character. But instead can we change this to a `log.Println`. This way if the standard go logger is redirected (like in billy), these messages will follow the same path.

2021-10-05 12:47 UTC, jlobraco commented on mmd/conn.go
> +		fmt.Printf("Unknown channel: %v discarding message", cid)
This will no longer print a newline character. But instead can we change this to a `log.Println`. This way if the standard go logger is redirected (like in billy), these messages will follow the same path.

2021-10-05 12:55 UTC, xizi-030 commented on mmd/conn.go
> +		fmt.Printf("Unknown channel: %v discarding message", cid)
Olga and I talked about this. this doesn't work with `go test` in go 1.16. 
```
$ go test ./...
# github.com/peak6/go-mmd/mmd
mmd/conn.go:352:3: Println call has possible formatting directive %v
mmd/conn.go:364:3: Println call has possible formatting directive %v
```
but instead of making code change we can also add `-vet=off` 
```
$ go test ./... -vet=off
?   	github.com/peak6/go-mmd/mmd	[no test files]
```

2021-10-05 13:06 UTC, jlobraco commented on mmd/conn.go
> +		fmt.Printf("Unknown channel: %v discarding message", cid)
Sorry. meant `log.Printf()`. The main thing is to change it from `fmt` to `log`. If you do that then the newline doesn't matter because the go logger will append on if it does not exist.

2021-10-05 14:25 UTC, pkuprys approved these changes
lgtm

2021-10-05 14:55 UTC, jlobraco approved these changes

2021-10-05 15:18 UTC, merged