fix deadlock within channel sendMsg path
peak6/go-mmd pull request #39
Opened 2022-08-19 20:06 UTC by minkeelee

https://peak6.slack.com/archives/GCR1S7YEM/p1660790387133519

https://peak6.atlassian.net/browse/PLAT-2235

2022-08-19 20:50 UTC, dan-dragan commented on mmd/conn.go
> +			continue
Consider counting the amount of retries and logging something every 100 or 1000 or so, so anyone troubleshooting why this hangs might have some inkling of the cause. I understand there's little to no chance of that occurring but I have been bit by potentially infinite loops before.

2022-08-19 20:51 UTC, dan-dragan commented on mmd/conn.go
> +			if attempts < 5 {
5 - consider making that configurable or at least a const #no-magic-numbers.

2022-08-19 20:51 UTC, dan-dragan commented on mmd/conn.go
> +				time.Sleep(100 * time.Millisecond)
100 #no-magic-numbers.

2022-08-22 13:21 UTC, jlobraco requested changes

2022-08-22 13:21 UTC, jlobraco commented on mmd/conn.go
> +func (c *ConnImpl) unregisterChannelAndSendMsgWithRetry(cid ChannelId, msg ChannelMsg) {
I'm not sure this is what we want here. This is the case of an mmd `Call`. If the receiver is not longer there this call will never succeed, and with this retry code it will spin forever.

Additionally, with the changes to the `unregisterChannelAndSendMsg` function, if the channel is not in the dispatchMap, this _will_ happen for certain.

2022-08-22 13:21 UTC, jlobraco commented on mmd/conn.go
> +		return false
This will cause the `lookupChannelAndSendMsgWithRetry` to try 5 times unnecessarily (logging an error each time).

2022-08-22 13:21 UTC, jlobraco commented on mmd/conn.go
> +		return false
This will cause `unregisterChannelAndSendMessageWithRetry` to loop forever and print an error every time.

2022-08-22 13:37 UTC, minkeelee commented on mmd/conn.go
> +		return false
if we return `false` here the calling `lookupChannelAndSendMsgWithRetry` will not go into the if conditional, and will return instead

2022-08-22 16:12 UTC, jlobraco approved these changes
Talked through it off-line, lgtm.

2022-08-22 21:11 UTC, ryant1986 approved these changes
looks good!

2022-08-24 13:53 UTC, pkuprys commented on mmd/conn.go
> +		if attempts % 100 == 0 {
Can we increment `attempts` after this check so we know we have entered this state?

2022-08-24 13:55 UTC, pkuprys requested changes
looks good, just one last thing

2022-08-25 19:52 UTC, merged